function Random_print(BestGuy, BestError)

% Function to print the best parameters of the current training

fprintf(  "Final Parameters: "+...
            mat2str(BestGuy{1})+", "+...
            BestGuy{2}+", "+...
            BestGuy{3}+", "+...
            BestGuy{4}+", "+...
            "with Validation Error: "+BestError +...
            "\n");
